### ISSUE TITLE
Specify a googleCalendarApiKey.

### ISSUE THREAD

**Issue by Melisunde** [stevewithington/MuraGoogleCalendar#1]
I've updated to the newest version of MuraGoogleCalendar but am getting an error in the console to "Specify a googleCalendarApiKey." It appears to be springing from the gcal.js file which is trying to set the API key with 'var apiKey = sourceOptions.googleCalendarApiKey || calendar.options.googleCalendarApiKey;' but it's not finding one.

The API key has been entered in the plugin's "Google Calendar API Key" field, and I know the key works because I can use it with cfhttp just fine. Any suggestions? Thanks!

**Comment by Melisunde** [comment]
Any thoughts? I'm still having this issue.

**Comment by stevewithington** [comment]
I've just tested the plugin again, and it's working fine for me. My suggestion would be:
1. Check to make sure your domain is listed as an authorized "referrer" in the Google Developers Console.
2. Also make sure you made your Google calendar "public"

Cheers,
Steve

**Comment by Melisunde** [comment]
Ah, I traced down the root of the problem; the plugin code was looking for
MuraGoogleCalendar.cfm but the file was named muraGoogleCalendar.cfm. I had
changed the capitalization of the file before so the plugin would find it,
but when I "updated" the plugin it was looking for the old renamed file and
not the updated correct-code-but-wrong-capitalization. (Yeah, I'm not on
Windows.) Thanks for your help, Steve.

On Tue, Apr 14, 2015 at 12:36 PM, Steve Withington <notifications@github.com

**Comment by stevewithington** [comment]
Ooops .. sorry about that. I do strive to maintain consistency on casing specifically because of that reason. I've just pushed a fix for that so it shouldn't happen again. Thanks!
