### ISSUE TITLE
No more XML files?

### ISSUE THREAD

**Issue by JonasEriksson** [stevewithington/MuraGoogleCalendar#2]
Hi Steve,
Unless I am mistaken, Google no longer issues XML feeds/URLs - is there a way to make this work? Or should we simply hold out for Mura 7? :-)

**Comment by IrjaGardner** [comment]
I need to know what to do about the Google Calendar XML feed (no longer available).  Please help.

**Comment by pattykirkey** [comment]
Under the Calendar Address section, next to the iCal and HTML buttons, there was a Calendar ID code that was generated. I was able to use this code instead of the XML code and it worked.

**Comment by stevewithington** [comment]
@JonasEriksson As @pattykirkey mentioned, you need to use the `Calendar ID` now. I'll be updating the plugin and instructions shortly. However, the Calendar ID looks something like `abcd1234@group.calendar.google.com`. Thanks!
