### ISSUE TITLE
New Google Calendar and XML

### ISSUE THREAD

**Issue by RedWombat** [stevewithington/MuraGoogleCalendar#3]
The new Google Calendar no longer supports the XML feed option.

Has this plug-in been updated to support the new Google Calendar API options?  If not, will it be?

Thank you,
Carl

**Comment by stevewithington** [comment]
@RedWombat I'll be updating the plugin, however, you should be using the `Calendar ID` instead now. It looks something like `abcd1234@group.calendar.google.com`. Instructions will be updated shortly. Thanks.
